VARIABLES_DATA = '''
{
    "CODERESP": {
        "0": "EINDDAT",
        "1": "SOURCE",
        "2": "Q00",
        "3": "Q00A",
        "4": "BLIND",
        "5": "Q59",
        "6": "Q59@",
        "7": "Q1",
        "8": "VARPERSON",
        "9": "Q2",
        "10": "Q4",
        "11": "Q4A_1",
        "12": "Q4A_2",
        "13": "Q5",
        "14": "Q6",
        "15": "Datum_treinreis",
        "16": "Dag_treinreis",
        "17": "Q8",
        "18": "Q8@",
        "19": "HQ8",
        "20": "dQ9A_01",
        "21": "dQ9A_02",
        "22": "dQ9A_03",
        "23": "dQ9A_04",
        "24": "dQ9A_05",
        "25": "dQ9A_06",
        "26": "dQ9A_07",
        "27": "Q9A_01",
        "28": "Q9A_02",
        "29": "Q9A_03",
        "30": "Q9A_04",
        "31": "Q9A_05",
        "32": "Q9A_06",
        "33": "Q10A",
        "34": "Q10",
        "35": "Q11",
        "36": "Q13A",
        "37": "Q13B",
        "38": "Q12A",
        "39": "Q12B",
        "40": "dQ13_01",
        "41": "dQ13_02",
        "42": "dQ13_03",
        "43": "dQ13_04",
        "44": "dQ13_05",
        "45": "dQ13_06",
        "46": "dQ13_07",
        "47": "dQ13_08",
        "48": "dQ13_09",
        "49": "dQ13_10",
        "50": "dQ13_11",
        "51": "dQ13_12",
        "52": "dQ13_13",
        "53": "dQ13_14",
        "54": "dQ13_15",
        "55": "dQ13_16",
        "56": "dQ13_17",
        "57": "dQ13_18",
        "58": "dQ13_19",
        "59": "Q13_01",
        "60": "Q13_02",
        "61": "Q13_03",
        "62": "Q13_04",
        "63": "Q13_05",
        "64": "Q13@",
        "65": "Q13C",
        "66": "Q13D",
        "67": "Q13E",
        "68": "ABOKAARTTOT",
        "69": "dQ14TXT_01",
        "70": "dQ14TXT_02",
        "71": "dQ14TXT_03",
        "72": "dQ14TXT_04",
        "73": "dQ14TXT_05",
        "74": "dQ14TXT_06",
        "75": "dQ14TXT_07",
        "76": "dQ14TXT_08",
        "77": "dQ14TXT_09",
        "78": "dQ14TXT_10",
        "79": "dQ14TXT_11",
        "80": "dQ14TXT_12",
        "81": "dQ14TXT_13",
        "82": "dQ14TXT_14",
        "83": "dQ14TXT_15",
        "84": "dQ14TXT_16",
        "85": "dQ14TXT_17",
        "86": "dQ14TXT_18",
        "87": "dQ14TXT_19",
        "88": "dQ14TXT_20",
        "89": "Q14TXT_01",
        "90": "Q14TXT_02",
        "91": "Q14TXT_03",
        "92": "Q14TXT_04",
        "93": "Q14TXT_05",
        "94": "Q14",
        "95": "Q15",
        "96": "Q20",
        "97": "Q20@",
        "98": "Q16B",
        "99": "Q16B@",
        "100": "Q16A",
        "101": "Q16A@",
        "102": "vertrekstation",
        "103": "vertrekstation_buitenland",
        "104": "aankomststation",
        "105": "aankomststation_buitenland",
        "106": "Q18B",
        "107": "Q18B@",
        "108": "PC_start_cijfers",
        "109": "PC_start_letters",
        "110": "Q18CC",
        "111": "Q18D",
        "112": "Q18D@",
        "113": "PC_bestemming_cijfers",
        "114": "PC_bestemming_letters",
        "115": "Q18EE",
        "116": "dQ18G_01",
        "117": "dQ18G_02",
        "118": "dQ18G_03",
        "119": "dQ18G_04",
        "120": "dQ18G_05",
        "121": "Q18G_01",
        "122": "Type_reis",
        "123": "Q24",
        "124": "Q21",
        "125": "dQ22_01",
        "126": "dQ22_02",
        "127": "dQ22_03",
        "128": "dQ22_04",
        "129": "dQ22_05",
        "130": "dQ22_06",
        "131": "dQ22_07",
        "132": "dQ22_08",
        "133": "dQ22_09",
        "134": "dQ22_10",
        "135": "dQ22_11",
        "136": "dQ22_12",
        "137": "dQ22_13",
        "138": "dQ22_14",
        "139": "Q22_01",
        "140": "Q22_02",
        "141": "Q22_03",
        "142": "Q22_04",
        "143": "Q22_05",
        "144": "Q22_06",
        "145": "Q22_07",
        "146": "Q22_08",
        "147": "Q22_09",
        "148": "Q22_10",
        "149": "Q22_11",
        "150": "Q22_12",
        "151": "Q22_13",
        "152": "Q22_14",
        "153": "Q22@",
        "154": "dQ22A_01",
        "155": "dQ22A_02",
        "156": "dQ22A_03",
        "157": "dQ22A_04",
        "158": "dQ22A_05",
        "159": "dQ22A_06",
        "160": "dQ22A_07",
        "161": "dQ22A_08",
        "162": "dQ22A_09",
        "163": "dQ22A_10",
        "164": "dQ22A_11",
        "165": "Q22A_01",
        "166": "Q22A_02",
        "167": "Q22A_03",
        "168": "Q22A_04",
        "169": "Q22A_05",
        "170": "Q22A_06",
        "171": "Q22A_07",
        "172": "Q22A_08",
        "173": "Q22A_09",
        "174": "Q22A_10",
        "175": "Q22A_11",
        "176": "Q22A@",
        "177": "dQ22B_01",
        "178": "dQ22B_02",
        "179": "dQ22B_03",
        "180": "dQ22B_04",
        "181": "dQ22B_05",
        "182": "dQ22B_06",
        "183": "dQ22B_07",
        "184": "dQ22B_08",
        "185": "dQ22B_09",
        "186": "dQ22B_10",
        "187": "Q22B_01",
        "188": "Q22B_02",
        "189": "Q22B_03",
        "190": "Q22B_04",
        "191": "Q22B_05",
        "192": "Q22B_06",
        "193": "Q22B_07",
        "194": "Q22B_08",
        "195": "Q22B_09",
        "196": "Q22B_10",
        "197": "Q22B@",
        "198": "Q25A",
        "199": "Q25B",
        "200": "Q25B@",
        "201": "Q25",
        "202": "Q25@",
        "203": "Q25C",
        "204": "Q25C@",
        "205": "Q25D",
        "206": "Q25D@",
        "207": "Q28A",
        "208": "Q28A@",
        "209": "Q28B",
        "210": "Q27A",
        "211": "Q27A@",
        "212": "Q27B",
        "213": "Q26",
        "214": "Q29",
        "215": "Q29@",
        "216": "Q30",
        "217": "hq30",
        "218": "dQ31_01",
        "219": "dQ31_02",
        "220": "dQ31_03",
        "221": "dQ31_04",
        "222": "dQ31_05",
        "223": "dQ31_06",
        "224": "dQ31_07",
        "225": "dQ31_08",
        "226": "dQ31_09",
        "227": "dQ31_10",
        "228": "dQ31_11",
        "229": "dQ31_12",
        "230": "dQ31_13",
        "231": "dQ31_14",
        "232": "dQ31_15",
        "233": "dQ31_16",
        "234": "dQ31_17",
        "235": "dQ31_18",
        "236": "dQ31_19",
        "237": "dQ31_20",
        "238": "dQ31_21",
        "239": "dQ31_22",
        "240": "Q31_01",
        "241": "Q31_02",
        "242": "Q31_03",
        "243": "Q31_04",
        "244": "Q31_05",
        "245": "Q31_06",
        "246": "Q31_07",
        "247": "Q31@",
        "248": "Q33",
        "249": "Q33@",
        "250": "Q34A",
        "251": "Q34",
        "252": "Q37",
        "253": "Q37@",
        "254": "Q38_1",
        "255": "Q39",
        "256": "Q40",
        "257": "Q41A",
        "258": "dQ41B_01",
        "259": "dQ41B_02",
        "260": "dQ41B_03",
        "261": "dQ41B_04",
        "262": "dQ41B_05",
        "263": "dQ41B_06",
        "264": "dQ41B_07",
        "265": "dQ41B_08",
        "266": "dQ41B_09",
        "267": "dQ41B_10",
        "268": "dQ41B_11",
        "269": "Q41B_01",
        "270": "Q41B_02",
        "271": "Q41B_03",
        "272": "Q41B_04",
        "273": "Q41B_05",
        "274": "Q41B_06",
        "275": "Q41B_07",
        "276": "Q41B_08",
        "277": "Q41B@",
        "278": "dQ41C_01",
        "279": "dQ41C_02",
        "280": "dQ41C_03",
        "281": "dQ41C_04",
        "282": "dQ41C_05",
        "283": "dQ41C_06",
        "284": "dQ41C_07",
        "285": "dQ41C_08",
        "286": "dQ41C_09",
        "287": "dQ41C_10",
        "288": "dQ41C_11",
        "289": "dQ41C_12",
        "290": "dQ41C_13",
        "291": "dQ41C_14",
        "292": "dQ41C_15",
        "293": "dQ41C_16",
        "294": "dQ41C_17",
        "295": "dQ41C_18",
        "296": "dQ41C_19",
        "297": "dQ41C_20",
        "298": "dQ41C_21",
        "299": "dQ41C_22",
        "300": "dQ41C_23",
        "301": "dQ41C_24",
        "302": "Q41C_01",
        "303": "Q41C_02",
        "304": "Q41C_03",
        "305": "Q41C_04",
        "306": "Q41C_05",
        "307": "Q41C_06",
        "308": "Q41C_07",
        "309": "Q41C_08",
        "310": "Q41C_09",
        "311": "Q41C_10",
        "312": "Q41C@",
        "313": "Q43",
        "314": "Q19",
        "315": "Q19@",
        "316": "dQ44_01",
        "317": "dQ44_02",
        "318": "dQ44_03",
        "319": "dQ44_04",
        "320": "dQ44_05",
        "321": "dQ44_06",
        "322": "dQ44_07",
        "323": "dQ44_08",
        "324": "dQ44_09",
        "325": "dQ44_10",
        "326": "dQ44_11",
        "327": "dQ44_12",
        "328": "dQ44_13",
        "329": "dQ44_14",
        "330": "dQ44_15",
        "331": "dQ44_16",
        "332": "dQ44_17",
        "333": "dQ44_18",
        "334": "dQ44_19",
        "335": "dQ44_20",
        "336": "dQ44_21",
        "337": "dQ44_22",
        "338": "dQ44_23",
        "339": "Q44_01",
        "340": "Q44_02",
        "341": "Q44_03",
        "342": "Q44_04",
        "343": "Q44_05",
        "344": "Q44_06",
        "345": "Q44_07",
        "346": "Q44_08",
        "347": "Q44_09",
        "348": "Q44_10",
        "349": "Q44@",
        "350": "Q47A",
        "351": "Q47B",
        "352": "Q47B@",
        "353": "Q47",
        "354": "Q47@",
        "355": "Q47C",
        "356": "Q47C@",
        "357": "Q47D",
        "358": "Q47D@",
        "359": "Q50A",
        "360": "Q50A@",
        "361": "Q50B",
        "362": "Q49A",
        "363": "Q49A@",
        "364": "Q49B",
        "365": "Q48",
        "366": "Q51",
        "367": "Q51@",
        "368": "Q52",
        "369": "dQ53A_01",
        "370": "dQ53A_02",
        "371": "dQ53A_03",
        "372": "dQ53A_04",
        "373": "dQ53A_05",
        "374": "dQ53A_06",
        "375": "dQ53A_07",
        "376": "dQ53A_08",
        "377": "dQ53A_09",
        "378": "dQ53A_10",
        "379": "dQ53A_11",
        "380": "dQ53A_12",
        "381": "dQ53A_13",
        "382": "dQ53A_14",
        "383": "Q53A_01",
        "384": "Q53A_02",
        "385": "Q53A_03",
        "386": "Q53A_04",
        "387": "Q53A_05",
        "388": "Q53A_06",
        "389": "Q53A_07",
        "390": "Q53A_08",
        "391": "Q53A@",
        "392": "Q53B",
        "393": "Q56_1",
        "394": "Q57",
        "395": "Q58",
        "396": "Q59A",
        "397": "Q59A@",
        "398": "Q60",
        "399": "Q61",
        "400": "Q62",
        "401": "Q62@",
        "402": "Q63",
        "403": "Q63@",
        "404": "Q63A",
        "405": "Q64",
        "406": "Q64@",
        "407": "Q65",
        "408": "Q65@",
        "409": "Q66_cijfers",
        "410": "Q66_letters",
        "411": "provinc",
        "412": "nielsen",
        "413": "stedpc",
        "414": "Q70@",
        "415": "weging22jun",
        "416": "VolgNr",
        "417": "Weekdag",
        "418": "Dagdeel",
        "419": "filter_$",
        "420": "LeeftCat"
    },
    "Respondent": {
        "0": "Einddatum",
        "1": "Panel",
        "2": "Gebruik screenreader software (q00)",
        "3": "Check blind of slechtziend (q00a)",
        "4": "Blind of slechtziend",
        "5": "Samenstelling huishouden (q59)",
        "6": "Andere samenstelling huishouden (q59)",
        "7": "Leeftijd oudste thuiswonende kind (q1)",
        "8": "Ingevuld voor volwassene of kind <16 jaar",
        "9": "Geslacht kind (q2)",
        "10": "Treinreisfrequentie afgelopen 12 maanden (q4)",
        "11": "Percentage reizen met NS (q4a)",
        "12": "Aandeel NS van alle treinreizen (q4a) Met andere vervoerders|%",
        "13": "Gisteren treinreis gemaakt (q5)",
        "14": "Laatst gemaakte treinreis (q6)",
        "15": "Datum treinreis",
        "16": "Dag treinreis",
        "17": "Reismotief trein afgelopen 12 maanden (hhq8)",
        "18": "Ander reismotief trein afgelopen 12 maanden (hhq8)",
        "19": "Reismotief trein afgelopen 12 maanden (hq8)",
        "20": "Soort vervoersbewijs (Q9a): OV-chipkaart: OV-chipkaart (met of zonder abonnement\/keuzedagen, met of zonder korting, anoniem of persoonlijk)",
        "21": "OV-studentenkaart",
        "22": "NS-Business Card",
        "23": "Andere Zakelijke OV-chipkaart",
        "24": "Losse kaartjes",
        "25": "OVpay",
        "26": "MISSING",
        "27": "Soort vervoersbewijs (Q9a): OV-chipkaart",
        "28": "OV-studentenkaart",
        "29": "NS-Business Card",
        "30": "Andere zakelijke OV-chipkaart",
        "31": "Losse kaartjes",
        "32": "OVpay",
        "33": "Aanbieder vervoersbewijs (q10a)",
        "34": "Type NS-Business card (q10)",
        "35": "Abonnement NS-Business Card (q11)",
        "36": "Soort studentenkaart (q13a)",
        "37": "Ander abonnement naast studentenreisproduct (q13b)",
        "38": "Persoonlijke OV-chipkaart (q12a)",
        "39": "Saldo laden (q12b)",
        "40": "Bezit abonnement (q13): Nee, geen abonnement",
        "41": "OV Studenten Weekabonnement",
        "42": "OV Studenten Weekendabonnement",
        "43": "Dal Voordeel abonnement",
        "44": "Voordeelurenabonnement",
        "45": "Traject Vrij jaarabonnement",
        "46": "Traject Vrij maandabonnement",
        "47": "Weekend Vrij abonnement",
        "48": "Dal Vrij abonnement",
        "49": "Altijd Voordeel abonnement",
        "50": "Altijd Vrij jaarabonnement",
        "51": "Altijd Vrij maandabonnement",
        "52": "Kids Vrij abonnement",
        "53": "NS Personeelsvervoerbewijs",
        "54": "NS Flex Basis",
        "55": "60+ Keuzedagen",
        "56": "Weekend Voordeel abonnement",
        "57": "Ander abonnement",
        "58": "Ander abonnement",
        "59": "Bezit abonnement (q13)",
        "60": "Bezit abonnement (q13)",
        "61": "Bezit abonnement (q13)",
        "62": "Bezit abonnement (q13)",
        "63": "Bezit abonnement (q13)",
        "64": "Bezit ander abonnement (q13)",
        "65": "Dal voordeel abonnement (q13c)",
        "66": "60+ Keuzedagen abonnement (q13d)",
        "67": "Weekend Vrij abonnement (q13e)",
        "68": "aboKaartTot",
        "69": "Getoonde abonnementen bij Q14: nee, geen abonnement",
        "70": "OV Studenten Weekabonnement",
        "71": "OV Studenten Weekendabonnement",
        "72": "Dal Voordeel abonnement",
        "73": "Voordeelurenabonnement",
        "74": "Traject Vrij jaarabonnement",
        "75": "Traject Vrij maandabonnement",
        "76": "Weekend Vrij abonnement",
        "77": "Dal Vrij abonnement",
        "78": "Altijd Voordeel abonnement",
        "79": "Altijd Vrij jaarabonnement",
        "80": "Altijd Vrij maandabonnement",
        "81": "Kids Vrij abonnement",
        "82": "NS Personeelsvervoerbewijs",
        "83": "soort NS Flex",
        "84": "NS Flex",
        "85": "soort NS-Business Card",
        "86": "NS-Business Card",
        "87": "Weekend Voordeel abonnement",
        "88": "anders",
        "89": "Getoonde abonnementen bij Q14",
        "90": "Getoonde abonnementen bij Q14",
        "91": "Getoonde abonnementen bij Q14",
        "92": "Getoonde abonnementen bij Q14",
        "93": "Getoonde abonnementen bij Q14",
        "94": "Check abonnement (q14)",
        "95": "Check reisdatum (q15)",
        "96": "Reismotief rit (q20)",
        "97": "Reismotief rit (q20)",
        "98": "Soort rit (q16b)",
        "99": "Andere soort rit (q16b)",
        "100": "Heen\/terugreis (q16a)",
        "101": "Heen of terugreis (q16a)",
        "102": "Vertrekstation (q17)",
        "103": "Vertrekstation buitenland (q17)",
        "104": "Aankomststation (q17)",
        "105": "Aankomststation buitenland (q17)",
        "106": "Naam startlocatie (q18b)",
        "107": "Naam startlocatie (q18b)",
        "108": "Postcode startlocatie heenreis - cijfers",
        "109": "Postcode startlocatie heenreis - letters",
        "110": "Startlocatie exact\/bij benadering (q18cc)",
        "111": "Naam eindbestemming (q18d)",
        "112": "Naam bestemming (q18d)",
        "113": "Postcode bestemming heenreis - cijfers",
        "114": "Postcode bestemming heenreis - letters",
        "115": "Eindbestemming exact\/bij benadering (q18ee)",
        "116": "Check volledige terugreis (q18g): Ja dit klopt",
        "117": "Nee, het traject per trein klopt niet (C naar B)",
        "118": "Nee, de bestemming van de terugreis klopt niet (A)",
        "119": "Nee, het startpunt voor de terugreis klopt niet (D)",
        "120": "Weet niet",
        "121": "Check volledige terugreis (q18g)",
        "122": "Type reis van deur naar deur",
        "123": "Tijdsduur op eindbestemming (q24)",
        "124": "Vooraf informatie opzoeken (q21)",
        "125": "Soort informatie opgezocht (q22): Kosten van de reis",
        "126": "Geplande vertrektijd",
        "127": "Aankomsttijd",
        "128": "Overstaptijd",
        "129": "Vertrekspoor",
        "130": "Lengte van en\/of drukte in de trein",
        "131": "Of mijn trein vertraging had",
        "132": "Stationsvoorzieningen van vertrek- en\/of aankomststation",
        "133": "Vervoersmogelijkheden van het station naar de bestemming of omgekeerd",
        "134": "Werkzaamheden\/verstoringen",
        "135": "Route van het station naar de bestemming of omgekeerd",
        "136": "Toegankelijkheid reis voor mensen met een beperking",
        "137": "anders",
        "138": "weet niet",
        "139": "Soort informatie opgezocht (q22)",
        "140": "Soort informatie opgezocht (q22)",
        "141": "Soort informatie opgezocht (q22)",
        "142": "Soort informatie opgezocht (q22)",
        "143": "Soort informatie opgezocht (q22)",
        "144": "Soort informatie opgezocht (q22)",
        "145": "Soort informatie opgezocht (q22)",
        "146": "Soort informatie opgezocht (q22)",
        "147": "Soort informatie opgezocht (q22)",
        "148": "Soort informatie opgezocht (q22)",
        "149": "Soort informatie opgezocht (q22)",
        "150": "Soort informatie opgezocht (q22)",
        "151": "Soort informatie opgezocht (q22)",
        "152": "Soort informatie opgezocht (q22)",
        "153": "Ander soort informatie opgezocht (q22)",
        "154": "Bron informatie opgezocht (q22a): NS app",
        "155": "9292 app",
        "156": "NS reisplanner op de website",
        "157": "9292 website",
        "158": "Google maps",
        "159": "Rijdendetreinen.nl",
        "160": "OVreisinfo.nl",
        "161": "Via familie, vrienden, collega\u2019s, kennissen",
        "162": "Via NS personeel\/klantenservice",
        "163": "anders",
        "164": "weet niet",
        "165": "Bron informatie opgezocht (q22a)",
        "166": "Bron informatie opgezocht (q22a)",
        "167": "Bron informatie opgezocht (q22a)",
        "168": "Bron informatie opgezocht (q22a)",
        "169": "Bron informatie opgezocht (q22a)",
        "170": "Bron informatie opgezocht (q22a)",
        "171": "Bron informatie opgezocht (q22a)",
        "172": "Bron informatie opgezocht (q22a)",
        "173": "Bron informatie opgezocht (q22a)",
        "174": "Bron informatie opgezocht (q22a)",
        "175": "Bron informatie opgezocht (q22a)",
        "176": "Andere bron informatie opgezocht (q22a)",
        "177": "Voorzieningen informatie opgezocht (q22b): OV-fiets huren",
        "178": "Stallen van mijn fiets",
        "179": "Parkeren van de auto",
        "180": "Eten en drinken op het station",
        "181": "Winkels op het station",
        "182": "Werken op het station",
        "183": "Voorzieningen minder validen",
        "184": "Mogelijkheden deelvervoer",
        "185": "Anders",
        "186": "Weet niet",
        "187": "Voorzieningen informatie opgezocht (q22b)",
        "188": "Voorzieningen informatie opgezocht (q22b)",
        "189": "Voorzieningen informatie opgezocht (q22b)",
        "190": "Voorzieningen informatie opgezocht (q22b)",
        "191": "Voorzieningen informatie opgezocht (q22b)",
        "192": "Voorzieningen informatie opgezocht (q22b)",
        "193": "Voorzieningen informatie opgezocht (q22b)",
        "194": "Voorzieningen informatie opgezocht (q22b)",
        "195": "Voorzieningen informatie opgezocht (q22b)",
        "196": "Voorzieningen informatie opgezocht (q22b)",
        "197": "Andere voorzieningen informatie opgezocht (q22b)",
        "198": "Zelfstanding naar station of meerijden (q25a)",
        "199": "Soort vervoermiddel gebracht (q25b)",
        "200": "Soort vervoermiddel gebracht (q25b)",
        "201": "Vervoermiddel naar station (q25)",
        "202": "Ander soort vervoermiddel gebracht (q25b)",
        "203": "Soort OV naar station (q25c)",
        "204": "Soort OV naar station (q25c)",
        "205": "Soort scooter naar station (q25d)",
        "206": "Soort scooter naar station (q25d)",
        "207": "Soort fiets naar station (q28a)",
        "208": "Soort fiets naar station (q28a)",
        "209": "Elektrische fiets of scooter (q28b)",
        "210": "Soort auto naar station (q27a)",
        "211": "Soort auto naar station (q27a)",
        "212": "Elektrische auto (q27b)",
        "213": "Reisduur naar station (q26)",
        "214": "Stalling vervoersmiddel (q29)",
        "215": "Andere stalling vervoersmiddel (q29)",
        "216": "Aantal minuten voor vertrek aanwezig op station (q30)",
        "217": "Aantal minuten voor vertrek trein op station (q30)",
        "218": "Tijdsbesteding station (q31): Saldo geladen op mijn OV-chipkaart",
        "219": "Treinkaartje(s) gekocht \/ Keuzedag geladen",
        "220": "Informatie over de trein geraadpleegd",
        "221": "Actief geweest op social media (Facebook, TikTok, Twitter, etc.)",
        "222": "Met iemand gepraat \/ op iemand gewacht",
        "223": "Eten of drinken gekocht",
        "224": "Non-food artikel(en) gekocht (krant, kantoorartikelen, kleding, sigaretten, etc.)",
        "225": "Gewinkeld zonder iets te kopen",
        "226": "Games of spelletjes gespeeld \/ film of serie gekeken (op telefoon, tablet, etc.)",
        "227": "Wat gelezen",
        "228": "Muziek geluisterd",
        "229": "Niets gedaan, beetje rondgekeken, gewoon gewacht",
        "230": "Gebeld, ge-sms\u2019t",
        "231": "In een horeca gelegenheid gezeten",
        "232": "Het toilet bezocht",
        "233": "Appen \/ internetten",
        "234": "Roken",
        "235": "Online meeting gevolgd \/ aan deelgenomen",
        "236": "Gewerkt (geen online meeting)",
        "237": "Direct in de trein gestapt",
        "238": "Anders",
        "239": "Dat weet ik niet (meer)",
        "240": "Tijdsbesteding station (q31)",
        "241": "Tijdsbesteding station (q31)",
        "242": "Tijdsbesteding station (q31)",
        "243": "Tijdsbesteding station (q31)",
        "244": "Tijdsbesteding station (q31)",
        "245": "Tijdsbesteding station (q31)",
        "246": "Tijdsbesteding station (q31)",
        "247": "Andere tijdsbesting station (q31)",
        "248": "Soort vervoersbewijs (q33)",
        "249": "Ander soort vervoersbewijs (q33)",
        "250": "Dagdeel vertrektijd trein (q34a)",
        "251": "Vertrektijd trein (q34)",
        "252": "Gezelschap treinreis (q37)",
        "253": "Ander gezelschap treinreis (q37)",
        "254": "Grootte gezelschap treinreis (q38)",
        "255": "1e of 2e klas (q39)",
        "256": "Stiltecoup\u00e9 (q40)",
        "257": "Tijdbesteding trein hoofdniveau (q41a)",
        "258": "Tijdbesteding trein werk (q41b): Bellen \/ chatten",
        "259": "Iets lezen op mobiele telefoon, laptop of tablet",
        "260": "Iets lezen van papier",
        "261": "Iets schrijven op mobiele telefoon, laptop of tablet",
        "262": "Iets schrijven op papier",
        "263": "E-mail lezen \/ sturen",
        "264": "Nadenken over werk\/studie",
        "265": "Overleg over werk studie met medepassagier\/collega",
        "266": "Online meeting gevolgd \/ aan deelgenomen",
        "267": "anders",
        "268": "weet niet",
        "269": "Tijdbesteding trein werk (q41b)",
        "270": "Tijdbesteding trein werk (q41b)",
        "271": "Tijdbesteding trein werk (q41b)",
        "272": "Tijdbesteding trein werk (q41b)",
        "273": "Tijdbesteding trein werk (q41b)",
        "274": "Tijdbesteding trein werk (q41b)",
        "275": "Tijdbesteding trein werk (q41b)",
        "276": "Tijdbesteding trein werk (q41b)",
        "277": "Andere tijdbesteding trein werk (q41b)",
        "278": "Tijdbesteding trein niet-werk (q41c): Bellen \/ sms-en",
        "279": "Actief geweest op social media",
        "280": "Whatsapp, Skype, Messenger gebruikt",
        "281": "E-mailen",
        "282": "Op internet gesurft",
        "283": "Online iets gekocht",
        "284": "Plannen van (vervolg) reis \/ terugreis",
        "285": "Lezen van een e-book \/ digitale krant",
        "286": "Video\/films\/serie bekeken",
        "287": "Naar muziek\/radio\/podcast geluisterd",
        "288": "Spelletjes gespeeld op mobiele telefoon, laptop of tablet",
        "289": "Krant, boek of tijdschrift gelezen",
        "290": "Gepraat",
        "291": "Voor medereizigers gezorgd",
        "292": "Gegeten, gedronken",
        "293": "Geslapen",
        "294": "Naar buiten gekeken, ontspannen, dagdromen",
        "295": "Gepuzzeld",
        "296": "Nadenken, zorgen maken over de reis",
        "297": "Het toilet bezocht",
        "298": "Handwerken",
        "299": "Helemaal niets gedaan",
        "300": "Anders",
        "301": "Weet niet",
        "302": "Tijdbesteding trein niet-werk (q41c)",
        "303": "Tijdbesteding trein niet-werk (q41c)",
        "304": "Tijdbesteding trein niet-werk (q41c)",
        "305": "Tijdbesteding trein niet-werk (q41c)",
        "306": "Tijdbesteding trein niet-werk (q41c)",
        "307": "Tijdbesteding trein niet-werk (q41c)",
        "308": "Tijdbesteding trein niet-werk (q41c)",
        "309": "Tijdbesteding trein niet-werk (q41c)",
        "310": "Tijdbesteding trein niet-werk (q41c)",
        "311": "Tijdbesteding trein niet-werk (q41c)",
        "312": "Andere tijdbesteding trein niet-werk (q41c)",
        "313": "Overstap (q43)",
        "314": "Grensstation (q19)",
        "315": "Grensstation (q19)",
        "316": "Bezigheid op aankomststation (q44): Niets, ik heb het station direct verlaten",
        "317": "Het station was mijn eindbestemming",
        "318": "Informatie over de trein geraadpleegd",
        "319": "Informatie over het bereiken van mijn eindbestemming gezocht",
        "320": "Actief geweest op social media",
        "321": "Op iemand gewacht \/ met iemand gepraat",
        "322": "Eten of drinken gekocht",
        "323": "Non-food artikel(en) gekocht",
        "324": "Gewinkeld zonder iets te kopen",
        "325": "Games of spelletjes gespeeld \/ film of serie gekeken",
        "326": "Wat gelezen",
        "327": "Muziek\/podcast geluisterd",
        "328": "Beetje rondgekeken",
        "329": "Gebeld, ge-sms\u2019t",
        "330": "In restauratie of caf\u00e9 gezeten",
        "331": "Het toilet bezocht",
        "332": "Wachten op bus \/ tram \/ metro",
        "333": "Online meeting gevolgd \/ aan deelgenomen",
        "334": "Gewerkt",
        "335": "Appen\/internetten",
        "336": "Roken",
        "337": "Anders",
        "338": "Weet niet",
        "339": "Bezigheid op aankomststation (q44)",
        "340": "Bezigheid op aankomststation (q44)",
        "341": "Bezigheid op aankomststation (q44)",
        "342": "Bezigheid op aankomststation (q44)",
        "343": "Bezigheid op aankomststation (q44)",
        "344": "Bezigheid op aankomststation (q44)",
        "345": "Bezigheid op aankomststation (q44)",
        "346": "Bezigheid op aankomststation (q44)",
        "347": "Bezigheid op aankomststation (q44)",
        "348": "Bezigheid op aankomststation (q44)",
        "349": "Andere bezigheid op aankomststation (q44)",
        "350": "Zelfstandig station of meerijden (q47a)",
        "351": "Soort vervoermiddel gebracht (q47b)",
        "352": "Soort vervoermiddel gebracht (q47b)",
        "353": "Vervoermiddel naar eindbestemming (q47)",
        "354": "Ander vervoermiddel naar eindbestemming (q47)",
        "355": "Soort OV naar station (q47c)",
        "356": "Soort OV naar station (q47c)",
        "357": "Soort scooter naar station (q47d)",
        "358": "Soort scooter naar station (q47d)",
        "359": "Elektrische fiets of scooter (q50a)",
        "360": "Soort fiets naar station (q50a)",
        "361": "Soort fiets naar station (q50b)",
        "362": "Soort auto naar station (q49a)",
        "363": "Ander soort auto naar station (q49a)",
        "364": "Elektrische auto (q49b)",
        "365": "Reistijd naar eindbestemming (q48)",
        "366": "Stalling vervoersmiddel (q51)",
        "367": "Stalling vervoersmiddel (q51)",
        "368": "Tijdsduur op eindbestemming (q52)",
        "369": "Alternatieven voor reis met de trein (q53a): Reis maken met de auto als bestuurder",
        "370": "Reis maken met de auto als passagier",
        "371": "Reis maken met de motor",
        "372": "Reis maken met de motor als passagier",
        "373": "Reis maken met de normale fiets",
        "374": "Reis maken met de elektrische fiets",
        "375": "Reis maken met de brommer, snorfiets of scooter",
        "376": "Reis maken met de bus\/metro\/tram\/snelbus\/Flixbus",
        "377": "Reis maken met het vliegtuig",
        "378": "Thuiswerken\/thuis school volgen",
        "379": "Geen alternatief",
        "380": "Reis maken met de taxi",
        "381": "anders",
        "382": "weet niet",
        "383": "Alternatieven voor reis met de trein (q53a)",
        "384": "Alternatieven voor reis met de trein (q53a)",
        "385": "Alternatieven voor reis met de trein (q53a)",
        "386": "Alternatieven voor reis met de trein (q53a)",
        "387": "Alternatieven voor reis met de trein (q53a)",
        "388": "Alternatieven voor reis met de trein (q53a)",
        "389": "Alternatieven voor reis met de trein (q53a)",
        "390": "Alternatieven voor reis met de trein (q53a)",
        "391": "Andere alternatieven voor reis met de trein (q53a)",
        "392": "Elektrische auto (q53b)",
        "393": "Leeftijd (q56)",
        "394": "Leeftijdscategorie (q57)",
        "395": "Geslacht (q58)",
        "396": "Huishouden thuiswonend kind (q59a)",
        "397": "Huishouden thuiswonend kind (q59a)",
        "398": "Grootte huishouden (q60)",
        "399": "Leeftijd jongste thuiswonende kind (q61)",
        "400": "Dagelijkse bezigheid (q62)",
        "401": "Andere dagelijkse bezigheid (q62)",
        "402": "Sector werkzaam (q63)",
        "403": "Andere sector werkzaam (q63)",
        "404": "Vitaal beroep k(q63a)",
        "405": "Studie nu bezig (q64)",
        "406": "Andere studie nu bezig (q64)",
        "407": "Afgeronde studie (q65)",
        "408": "Afgeronde studie (q65)",
        "409": "Postcode woonadres cijfers",
        "410": "Postcode woonadres letters",
        "411": "Indeling in provincies",
        "412": "Nielsen regio-indeling",
        "413": "Stedelijkheidsgraad (postcode)",
        "414": "Opmerkingen onderzoek (q70)",
        "415": "Weegfactor Ritten versie 22 juni",
        "416": "Volgnummer",
        "417": "Dag van de week",
        "418": "Dagdeel",
        "419": "Dagdeel=1 and (Weekdag=3 or weekdag=5) (FILTER)",
        "420": "Leeftijdscategorie"
    }
}
'''

RITTEN_DATA = '''
{
    "CODERESP": {
        "0": 868079,
        "1": 937709,
        "2": 1056998,
        "3": 302286,
        "4": 502714,
        "5": 1054800,
        "6": 505208,
        "7": 523744,
        "8": 828641,
        "9": 907007
    },
    "Q59": {
        "0": "Ikzelf met partner en kind(eren) (ook deeltijdzorg)",
        "1": "Ikzelf met kind(eren) (ook deeltijdzorg)",
        "2": "Ikzelf met partner en kind(eren) (ook deeltijdzorg)",
        "3": "Ikzelf met partner en kind(eren) (ook deeltijdzorg)",
        "4": "Ikzelf met partner en kind(eren) (ook deeltijdzorg)",
        "5": "Ikzelf met kind(eren) (ook deeltijdzorg)",
        "6": "Ikzelf met partner en kind(eren) (ook deeltijdzorg)",
        "7": "Ikzelf met partner en kind(eren) (ook deeltijdzorg)",
        "8": "Ikzelf met partner en kind(eren) (ook deeltijdzorg)",
        "9": "Ikzelf met partner en kind(eren) (ook deeltijdzorg)"
    },
    "Q2": {
        "0": "Een jongen",
        "1": "Een jongen",
        "2": "Een meisje",
        "3": "Een meisje",
        "4": "Wil niet zeggen",
        "5": "Een meisje",
        "6": "Een jongen",
        "7": "Een meisje",
        "8": "Een meisje",
        "9": "Een jongen"
    },
    "Q4": {
        "0": "1 - 3 dagen per week",
        "1": "1 of 2 dagen in de afgelopen 12 maanden",
        "2": "6 - 11 dagen in de afgelopen 12 maanden",
        "3": "3 - 5 dagen in de afgelopen 12 maanden",
        "4": "1 - 3 dagen per week",
        "5": "6 - 11 dagen in de afgelopen 12 maanden",
        "6": "1 - 3 dagen per maand",
        "7": "6 - 11 dagen in de afgelopen 12 maanden",
        "8": "1 - 3 dagen per maand",
        "9": "6 - 11 dagen in de afgelopen 12 maanden"
    },
    "Q4A_1": {
        "0": 100,
        "1": 100,
        "2": 100,
        "3": 100,
        "4": "Weet ik niet",
        "5": 100,
        "6": 100,
        "7": 90,
        "8": 50,
        "9": 90
    },
    "Q4A_2": {
        "0": 0,
        "1": 0,
        "2": 0,
        "3": 0,
        "4": "Weet ik niet",
        "5": 0,
        "6": 0,
        "7": 10,
        "8": 50,
        "9": 10
    },
    "Q5": {
        "0": "Nee",
        "1": "Nee",
        "2": "Nee",
        "3": "Nee",
        "4": "Nee",
        "5": "Nee",
        "6": "Nee",
        "7": "Nee",
        "8": "Nee",
        "9": "Nee"
    },
    "Q6": {
        "0": "Vandaag",
        "1": "1-2 maanden geleden",
        "2": "Vorige week",
        "3": "1-2 maanden geleden",
        "4": "Ongeveer 4 weken geleden",
        "5": "Ongeveer 2 weken geleden",
        "6": "Ongeveer 3 weken geleden",
        "7": "1-2 maanden geleden",
        "8": "Vorige week",
        "9": "Ongeveer 4 weken geleden"
    },
    "Datum_treinreis": {
        "0": "zaterdag 04-02-2023",
        "1": "woensdag 28-12-2022",
        "2": "zaterdag 18-02-2023",
        "3": "zondag 11-12-2022",
        "4": "dinsdag 13-12-2022",
        "5": "zondag 12-02-2023",
        "6": "donderdag 05-01-2023",
        "7": "dinsdag 27-12-2022",
        "8": "zaterdag 28-01-2023",
        "9": "woensdag 25-01-2023"
    },
    "Dag_treinreis": {
        "0": "zaterdag",
        "1": "woensdag",
        "2": "zaterdag",
        "3": "zondag",
        "4": "dinsdag",
        "5": "zondag",
        "6": "donderdag",
        "7": "dinsdag",
        "8": "zaterdag",
        "9": "woensdag"
    },
    "Q8": {
        "0": "Van\/naar school, studie, cursus, opleiding",
        "1": "Winkelen\/vakantie\/uitstapjes\/dagje weg\/museum\/wandelen",
        "2": "Bezoek aan familie\/vrienden\/kennissen, sport\/hobby, medische reden, zorgtaken, kerk",
        "3": "Bezoek aan familie\/vrienden\/kennissen, sport\/hobby, medische reden, zorgtaken, kerk",
        "4": "Van\/naar school, studie, cursus, opleiding",
        "5": "Bezoek aan familie\/vrienden\/kennissen, sport\/hobby, medische reden, zorgtaken, kerk",
        "6": "Bezoek aan familie\/vrienden\/kennissen, sport\/hobby, medische reden, zorgtaken, kerk",
        "7": "Bezoek aan familie\/vrienden\/kennissen, sport\/hobby, medische reden, zorgtaken, kerk",
        "8": "Bezoek aan familie\/vrienden\/kennissen, sport\/hobby, medische reden, zorgtaken, kerk",
        "9": "Bezoek aan familie\/vrienden\/kennissen, sport\/hobby, medische reden, zorgtaken, kerk"
    },
    "Q8@": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "HQ8": {
        "0": "woon-school",
        "1": "recreatief",
        "2": "sociaal",
        "3": "sociaal",
        "4": "woon-school",
        "5": "sociaal",
        "6": "sociaal",
        "7": "sociaal",
        "8": "sociaal",
        "9": "sociaal"
    },
    "Q10": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "Q11": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "Q13A": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "Q13B": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "Q12A": {
        "0": "Persoonlijke OV-chipkaart",
        "1": "Persoonlijke OV-chipkaart",
        "2": "Persoonlijke OV-chipkaart",
        "3": "Persoonlijke OV-chipkaart",
        "4": "Persoonlijke OV-chipkaart",
        "5": "Persoonlijke OV-chipkaart",
        "6": "Persoonlijke OV-chipkaart",
        "7": "Persoonlijke OV-chipkaart",
        "8": "Persoonlijke OV-chipkaart",
        "9": "Persoonlijke OV-chipkaart"
    },
    "Q12B": {
        "0": "Ja, bij de kaartautomaat of de balie",
        "1": "Nee, de reizen worden achteraf per maand via automatische incasso betaald",
        "2": "Ja, bij de kaartautomaat of de balie",
        "3": "Ja, via automatisch saldo laden",
        "4": "Weet niet",
        "5": "Ja, bij de kaartautomaat of de balie",
        "6": "Ja, bij de kaartautomaat of de balie",
        "7": "Ja, bij de kaartautomaat of de balie",
        "8": "Nee, de reizen worden achteraf per maand via automatische incasso betaald",
        "9": "Ja, bij de kaartautomaat of de balie"
    },
    "Q20": {
        "0": "Naar school, studie, opleiding, stage",
        "1": "Winkelen",
        "2": "Bezoek aan familie, vrienden, kennissen",
        "3": "Bezoek aan familie, vrienden, kennissen",
        "4": "Naar school, studie, opleiding, stage",
        "5": "Bezoek aan familie, vrienden, kennissen",
        "6": "Bezoek aan familie, vrienden, kennissen",
        "7": "Bezoek aan familie, vrienden, kennissen",
        "8": "Winkelen",
        "9": "Bezoek aan familie, vrienden, kennissen"
    },
    "Q16B": {
        "0": "Retourreis op hetzelfde traject",
        "1": "Retourreis op hetzelfde traject",
        "2": "Retourreis op hetzelfde traject",
        "3": "Enkele reis",
        "4": "Retourreis op hetzelfde traject",
        "5": "Enkele reis",
        "6": "Retourreis op hetzelfde traject",
        "7": "Enkele reis",
        "8": "Retourreis op hetzelfde traject",
        "9": "Enkele reis"
    },
    "Q16A": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": "Heenreis, ik ben op een andere manier teruggereisd",
        "4": " ",
        "5": "Terugreis, ik ben wel met de trein heen gereisd maar dat was op een andere dag",
        "6": " ",
        "7": "Terugreis, ik ben wel met de trein heen gereisd maar dat was op een andere dag",
        "8": " ",
        "9": "Terugreis, ik ben op een andere manier heen gereisd"
    },
    "vertrekstation": {
        "0": "Rotterdam Centraal",
        "1": "Apeldoorn",
        "2": "Den Haag Ypenburg",
        "3": "Bilthoven",
        "4": "Apeldoorn",
        "5": "Deurne",
        "6": "Amsterdam Centraal",
        "7": "Beilen",
        "8": "Zutphen",
        "9": "Utrecht Centraal"
    },
    "vertrekstation_buitenland": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "aankomststation": {
        "0": "Delft",
        "1": "Rijssen",
        "2": "Gouda",
        "3": "Soest",
        "4": "Almelo",
        "5": "Den Haag Centraal",
        "6": "s Hertogenbosch",
        "7": "Groningen",
        "8": "Apeldoorn De Maten",
        "9": "Amersfoort Centraal"
    },
    "aankomststation_buitenland": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "Q18B": {
        "0": "Thuis",
        "1": "Thuis",
        "2": "Thuis",
        "3": "Thuis",
        "4": "Thuis",
        "5": "Familie",
        "6": "Thuis",
        "7": "Familie",
        "8": "Thuis",
        "9": "Anders"
    },
    "PC_start_cijfers": {
        "0": "Wil ik niet zeggen",
        "1": "Wil ik niet zeggen",
        "2": 2612,
        "3": "Wil ik niet zeggen",
        "4": "Wil ik niet zeggen",
        "5": "Wil ik niet zeggen",
        "6": "Wil ik niet zeggen",
        "7": 7938,
        "8": "Wil ik niet zeggen",
        "9": "Wil ik niet zeggen"
    },
    "Q18CC": {
        "0": " ",
        "1": " ",
        "2": "Nee, alleen de postcodecijfers kloppen maar de letters (waarschijnlijk) niet",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": "Ja dat mag. Dit is de exacte locatie of de locatie ligt dicht in de buurt",
        "8": " ",
        "9": " "
    },
    "Q18D": {
        "0": "School\/studie\/opleiding",
        "1": "Stadscentrum",
        "2": "Familie",
        "3": "Vriend(en)\/vriendin(en)\/kennissen",
        "4": "School\/studie\/opleiding",
        "5": "Huis",
        "6": "Familie",
        "7": "Huis",
        "8": "Winkelcentrum",
        "9": "Huis"
    },
    "PC_bestemming_cijfers": {
        "0": "Wil ik niet zeggen",
        "1": "Wil ik niet zeggen",
        "2": 2804,
        "3": "Wil ik niet zeggen",
        "4": "Wil ik niet zeggen",
        "5": "Wil ik niet zeggen",
        "6": "Wil ik niet zeggen",
        "7": 9742,
        "8": "Wil ik niet zeggen",
        "9": "Wil ik niet zeggen"
    },
    "Q18EE": {
        "0": " ",
        "1": " ",
        "2": "Ja dat mag. Dit is de exacte locatie of de locatie ligt dicht in de buurt",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": "Nee, alleen de postcodecijfers kloppen maar de letters (waarschijnlijk) niet",
        "8": " ",
        "9": " "
    },
    "dQ18G_01": {
        "0": "gekozen",
        "1": "gekozen",
        "2": "gekozen",
        "3": " ",
        "4": "gekozen",
        "5": " ",
        "6": "gekozen",
        "7": " ",
        "8": "gekozen",
        "9": " "
    },
    "dQ18G_02": {
        "0": "niet gekozen",
        "1": "niet gekozen",
        "2": "niet gekozen",
        "3": " ",
        "4": "niet gekozen",
        "5": " ",
        "6": "niet gekozen",
        "7": " ",
        "8": "niet gekozen",
        "9": " "
    },
    "dQ18G_03": {
        "0": "niet gekozen",
        "1": "niet gekozen",
        "2": "niet gekozen",
        "3": " ",
        "4": "niet gekozen",
        "5": " ",
        "6": "niet gekozen",
        "7": " ",
        "8": "niet gekozen",
        "9": " "
    },
    "dQ18G_04": {
        "0": "niet gekozen",
        "1": "niet gekozen",
        "2": "niet gekozen",
        "3": " ",
        "4": "niet gekozen",
        "5": " ",
        "6": "niet gekozen",
        "7": " ",
        "8": "niet gekozen",
        "9": " "
    },
    "dQ18G_05": {
        "0": "niet gekozen",
        "1": "niet gekozen",
        "2": "niet gekozen",
        "3": " ",
        "4": "niet gekozen",
        "5": " ",
        "6": "niet gekozen",
        "7": " ",
        "8": "niet gekozen",
        "9": " "
    },
    "Q18G_01": {
        "0": "Ja dit klopt",
        "1": "Ja dit klopt",
        "2": "Ja dit klopt",
        "3": " ",
        "4": "Ja dit klopt",
        "5": " ",
        "6": "Ja dit klopt",
        "7": " ",
        "8": "Ja dit klopt",
        "9": " "
    },
    "Type_reis": {
        "0": "terugreis retour",
        "1": "terugreis retour",
        "2": "terugreis retour",
        "3": "heenreis",
        "4": "terugreis retour",
        "5": "terugreis enkel",
        "6": "terugreis retour",
        "7": "terugreis enkel",
        "8": "terugreis retour",
        "9": "terugreis enkel"
    },
    "Q24": {
        "0": "4 tot 6 uur",
        "1": "Minder dan 1 uur",
        "2": "1 tot 2 uur",
        "3": " ",
        "4": "1 tot 2 uur",
        "5": "10 uur of langer",
        "6": "6 tot 8 uur",
        "7": "10 uur of langer",
        "8": "Weet niet",
        "9": "1 tot 2 uur"
    },
    "Q21": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ22_01": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ22_02": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ22_03": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ22_04": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ22_05": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ22_06": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ22_07": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ22_08": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ22_09": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ22_10": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ22_11": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ22_12": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ22_13": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ22_14": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ22A_01": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ22A_02": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ22A_03": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ22A_04": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ22A_05": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ22A_06": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ22A_07": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ22A_08": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ22A_09": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ22A_10": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ22A_11": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ22B_01": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ22B_02": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ22B_03": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ22B_04": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ22B_05": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ22B_06": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ22B_07": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ22B_08": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ22B_09": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ22B_10": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "Q25A": {
        "0": "Gebracht \/  kon meerijden",
        "1": "Gebracht \/  kon meerijden",
        "2": "Gebracht \/  kon meerijden",
        "3": "Gebracht \/  kon meerijden",
        "4": "Zelf naar het station gegaan",
        "5": "Gebracht \/  kon meerijden",
        "6": "Gebracht \/  kon meerijden",
        "7": "Gebracht \/  kon meerijden",
        "8": "Zelf naar het station gegaan",
        "9": "Zelf naar het station gegaan"
    },
    "Q25B": {
        "0": "Fiets",
        "1": "Lopend",
        "2": "Fiets",
        "3": "Auto",
        "4": " ",
        "5": "Auto",
        "6": "Fiets",
        "7": "Auto",
        "8": " ",
        "9": " "
    },
    "Q25": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": "Lopend",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": "Lopend",
        "9": "Met de taxi, NS zonetaxi, regiotaxi"
    },
    "Q25C": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "Q25D": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "Q28A": {
        "0": "Gewone eigen fiets",
        "1": " ",
        "2": "Gewone eigen fiets",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": "Bakfiets",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "Q28B": {
        "0": "Nee",
        "1": " ",
        "2": "Nee",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": "Nee",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "Q27A": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": "Eigen auto \/ leaseauto",
        "4": " ",
        "5": "Eigen auto \/ leaseauto",
        "6": " ",
        "7": "Eigen auto \/ leaseauto",
        "8": " ",
        "9": " "
    },
    "Q27B": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": "Nee",
        "4": " ",
        "5": "Deels, een hybride auto",
        "6": " ",
        "7": "Nee",
        "8": " ",
        "9": " "
    },
    "Q26": {
        "0": "Weet niet",
        "1": "Minder dan 10 minuten",
        "2": "Minder dan 10 minuten",
        "3": "10 tot 20 minuten",
        "4": "10 tot 20 minuten",
        "5": "10 tot 20 minuten",
        "6": "20 tot 30 minuten",
        "7": "10 tot 20 minuten",
        "8": "10 tot 20 minuten",
        "9": "Een uur of langer"
    },
    "Q29": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "Q30": {
        "0": "net op tijd om de trein te halen",
        "1": "net op tijd om de trein te halen",
        "2": "net op tijd om de trein te halen",
        "3": 5,
        "4": 5,
        "5": 5,
        "6": 10,
        "7": 10,
        "8": "dat weet ik niet (meer)",
        "9": "dat weet ik niet (meer)"
    },
    "hq30": {
        "0": "0-5 minuten",
        "1": "0-5 minuten",
        "2": "0-5 minuten",
        "3": "0-5 minuten",
        "4": "0-5 minuten",
        "5": "0-5 minuten",
        "6": "6-10 minuten",
        "7": "6-10 minuten",
        "8": "weet niet",
        "9": "weet niet"
    },
    "dQ31_01": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ31_02": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ31_03": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ31_04": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ31_05": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ31_06": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ31_07": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ31_08": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ31_09": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ31_10": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ31_11": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ31_12": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ31_13": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ31_14": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ31_15": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ31_16": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ31_17": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ31_18": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ31_19": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ31_20": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ31_21": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ31_22": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "Q33": {
        "0": "Met het abonnement",
        "1": "Met het abonnement",
        "2": "Met het abonnement",
        "3": "Met het abonnement",
        "4": "Met het abonnement",
        "5": "Met het abonnement",
        "6": "Met het abonnement",
        "7": "Met het abonnement",
        "8": "Met het abonnement",
        "9": "Met het abonnement"
    },
    "Q34A": {
        "0": "onbekend",
        "1": "onbekend",
        "2": "onbekend",
        "3": "onbekend",
        "4": "onbekend",
        "5": "onbekend",
        "6": "onbekend",
        "7": "onbekend",
        "8": "onbekend",
        "9": "onbekend"
    },
    "Q34": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "Q37": {
        "0": "Samen met familieleden",
        "1": "Samen met familieleden",
        "2": "Samen met familieleden",
        "3": "Alleen",
        "4": "Samen met familieleden",
        "5": "Samen met familieleden",
        "6": "Samen met familieleden",
        "7": "Samen met familieleden",
        "8": "Samen met familieleden",
        "9": "Samen met vrienden of kennissen"
    },
    "Q38_1": {
        "0": "Weet niet (meer)",
        "1": 3,
        "2": 2,
        "3": 1,
        "4": "Weet niet (meer)",
        "5": 4,
        "6": 4,
        "7": 3,
        "8": 1,
        "9": 3
    },
    "Q39": {
        "0": "2e klas",
        "1": "2e klas",
        "2": "2e klas",
        "3": "2e klas",
        "4": "2e klas",
        "5": "2e klas",
        "6": "2e klas",
        "7": "2e klas",
        "8": "2e klas",
        "9": "2e klas"
    },
    "Q40": {
        "0": "Nee",
        "1": "Nee",
        "2": "Nee",
        "3": "Nee",
        "4": "Deel van de rit in een stiltecoup\u00e9 en een deel in een gewone coup\u00e9",
        "5": "Nee",
        "6": "Nee",
        "7": "Nee",
        "8": "Nee",
        "9": "Nee"
    },
    "Q41A": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ41B_01": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ41B_02": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ41B_03": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ41B_04": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ41B_05": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ41B_06": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ41B_07": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ41B_08": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ41B_09": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ41B_10": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ41B_11": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ41C_01": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ41C_02": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ41C_03": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ41C_04": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ41C_05": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ41C_06": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ41C_07": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ41C_08": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ41C_09": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ41C_10": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ41C_11": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ41C_12": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ41C_13": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ41C_14": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ41C_15": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ41C_16": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ41C_17": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ41C_18": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ41C_19": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ41C_20": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ41C_21": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ41C_22": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ41C_23": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ41C_24": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "Q43": {
        "0": "niet",
        "1": "niet",
        "2": "niet",
        "3": "niet",
        "4": "niet",
        "5": "1 keer",
        "6": "niet",
        "7": "niet",
        "8": "niet",
        "9": "niet"
    },
    "Q19": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ44_01": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ44_02": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ44_03": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ44_04": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ44_05": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ44_06": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ44_07": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ44_08": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ44_09": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ44_10": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ44_11": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ44_12": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ44_13": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ44_14": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ44_15": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ44_16": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ44_17": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ44_18": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ44_19": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ44_20": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ44_21": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ44_22": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ44_23": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "Q47A": {
        "0": "Ben opgehaald \/ kon meerijden",
        "1": "Ben opgehaald \/ kon meerijden",
        "2": "Ben opgehaald \/ kon meerijden",
        "3": "Ben opgehaald \/ kon meerijden",
        "4": "Ben opgehaald \/ kon meerijden",
        "5": "Ben opgehaald \/ kon meerijden",
        "6": "Ben opgehaald \/ kon meerijden",
        "7": "Ben opgehaald \/ kon meerijden",
        "8": "Ben opgehaald \/ kon meerijden",
        "9": "Ben opgehaald \/ kon meerijden"
    },
    "Q47B": {
        "0": "Fiets",
        "1": "Fiets",
        "2": "Fiets",
        "3": "Fiets",
        "4": "Fiets",
        "5": "Fiets",
        "6": "Fiets",
        "7": "Fiets",
        "8": "Fiets",
        "9": "Fiets"
    },
    "Q47": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "Q47C": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "Q47D": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "Q50A": {
        "0": "Gewone eigen fiets",
        "1": "Gewone eigen fiets",
        "2": "Gewone eigen fiets",
        "3": "Gewone eigen fiets",
        "4": "Gewone eigen fiets",
        "5": "Gewone eigen fiets",
        "6": "Bakfiets",
        "7": "Gewone eigen fiets",
        "8": "Gewone eigen fiets",
        "9": "Gewone eigen fiets"
    },
    "Q50B": {
        "0": "Nee",
        "1": "Nee",
        "2": "Nee",
        "3": "Nee",
        "4": "Nee",
        "5": "Ja, elektrisch",
        "6": "Nee",
        "7": "Nee",
        "8": "Nee",
        "9": "Nee"
    },
    "Q49A": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "Q49B": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "Q48": {
        "0": "Weet niet (meer)",
        "1": "Minder dan 10 minuten",
        "2": "20 tot 30 minuten",
        "3": "Minder dan 10 minuten",
        "4": "Minder dan 10 minuten",
        "5": "10 tot 20 minuten",
        "6": "10 tot 20 minuten",
        "7": "20 tot 30 minuten",
        "8": "10 tot 20 minuten",
        "9": "10 tot 20 minuten"
    },
    "Q51": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "Q52": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": "4 tot 6 uur",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "dQ53A_01": {
        "0": "niet gekozen",
        "1": "niet gekozen",
        "2": "niet gekozen",
        "3": "niet gekozen",
        "4": "niet gekozen",
        "5": "niet gekozen",
        "6": "niet gekozen",
        "7": "niet gekozen",
        "8": "niet gekozen",
        "9": "niet gekozen"
    },
    "dQ53A_02": {
        "0": "niet gekozen",
        "1": "niet gekozen",
        "2": "niet gekozen",
        "3": "gekozen",
        "4": "niet gekozen",
        "5": "niet gekozen",
        "6": "niet gekozen",
        "7": "niet gekozen",
        "8": "niet gekozen",
        "9": "niet gekozen"
    },
    "dQ53A_03": {
        "0": "niet gekozen",
        "1": "niet gekozen",
        "2": "niet gekozen",
        "3": "niet gekozen",
        "4": "niet gekozen",
        "5": "niet gekozen",
        "6": "niet gekozen",
        "7": "niet gekozen",
        "8": "niet gekozen",
        "9": "niet gekozen"
    },
    "dQ53A_04": {
        "0": "niet gekozen",
        "1": "niet gekozen",
        "2": "niet gekozen",
        "3": "niet gekozen",
        "4": "niet gekozen",
        "5": "niet gekozen",
        "6": "niet gekozen",
        "7": "niet gekozen",
        "8": "niet gekozen",
        "9": "niet gekozen"
    },
    "dQ53A_05": {
        "0": "niet gekozen",
        "1": "niet gekozen",
        "2": "niet gekozen",
        "3": "gekozen",
        "4": "niet gekozen",
        "5": "niet gekozen",
        "6": "niet gekozen",
        "7": "niet gekozen",
        "8": "niet gekozen",
        "9": "niet gekozen"
    },
    "dQ53A_06": {
        "0": "niet gekozen",
        "1": "niet gekozen",
        "2": "niet gekozen",
        "3": "niet gekozen",
        "4": "niet gekozen",
        "5": "niet gekozen",
        "6": "niet gekozen",
        "7": "niet gekozen",
        "8": "niet gekozen",
        "9": "niet gekozen"
    },
    "dQ53A_07": {
        "0": "niet gekozen",
        "1": "niet gekozen",
        "2": "niet gekozen",
        "3": "niet gekozen",
        "4": "niet gekozen",
        "5": "niet gekozen",
        "6": "niet gekozen",
        "7": "niet gekozen",
        "8": "niet gekozen",
        "9": "niet gekozen"
    },
    "dQ53A_08": {
        "0": "niet gekozen",
        "1": "niet gekozen",
        "2": "gekozen",
        "3": "niet gekozen",
        "4": "niet gekozen",
        "5": "gekozen",
        "6": "niet gekozen",
        "7": "gekozen",
        "8": "niet gekozen",
        "9": "niet gekozen"
    },
    "dQ53A_09": {
        "0": "niet gekozen",
        "1": "niet gekozen",
        "2": "niet gekozen",
        "3": "niet gekozen",
        "4": "niet gekozen",
        "5": "niet gekozen",
        "6": "niet gekozen",
        "7": "niet gekozen",
        "8": "niet gekozen",
        "9": "niet gekozen"
    },
    "dQ53A_10": {
        "0": "niet gekozen",
        "1": "niet gekozen",
        "2": "niet gekozen",
        "3": "niet gekozen",
        "4": "niet gekozen",
        "5": "niet gekozen",
        "6": "niet gekozen",
        "7": "niet gekozen",
        "8": "niet gekozen",
        "9": "niet gekozen"
    },
    "dQ53A_11": {
        "0": "niet gekozen",
        "1": "gekozen",
        "2": "niet gekozen",
        "3": "niet gekozen",
        "4": "niet gekozen",
        "5": "niet gekozen",
        "6": "gekozen",
        "7": "niet gekozen",
        "8": "gekozen",
        "9": "niet gekozen"
    },
    "dQ53A_12": {
        "0": "niet gekozen",
        "1": "niet gekozen",
        "2": "niet gekozen",
        "3": "niet gekozen",
        "4": "niet gekozen",
        "5": "niet gekozen",
        "6": "niet gekozen",
        "7": "niet gekozen",
        "8": "niet gekozen",
        "9": "gekozen"
    },
    "dQ53A_13": {
        "0": "niet gekozen",
        "1": "niet gekozen",
        "2": "niet gekozen",
        "3": "niet gekozen",
        "4": "niet gekozen",
        "5": "niet gekozen",
        "6": "niet gekozen",
        "7": "niet gekozen",
        "8": "niet gekozen",
        "9": "niet gekozen"
    },
    "dQ53A_14": {
        "0": "gekozen",
        "1": "niet gekozen",
        "2": "niet gekozen",
        "3": "niet gekozen",
        "4": "gekozen",
        "5": "niet gekozen",
        "6": "niet gekozen",
        "7": "niet gekozen",
        "8": "niet gekozen",
        "9": "niet gekozen"
    },
    "Q53B": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": "Nee",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "Q58": {
        "0": "Man",
        "1": "Man",
        "2": "Vrouw",
        "3": "Vrouw",
        "4": "Wil niet zeggen",
        "5": "Vrouw",
        "6": "Man",
        "7": "Vrouw",
        "8": "Vrouw",
        "9": "Man"
    },
    "Q59A": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "Q60": {
        "0": "3 personen",
        "1": "4 personen",
        "2": "4 personen",
        "3": "3 personen",
        "4": "4 personen",
        "5": "2 personen",
        "6": "4 personen",
        "7": "4 personen",
        "8": "3 personen",
        "9": "4 personen"
    },
    "Q61": {
        "0": "6 \u2013 12 jaar",
        "1": "0 \u2013 3 jaar",
        "2": "6 \u2013 12 jaar",
        "3": "6 \u2013 12 jaar",
        "4": "6 \u2013 12 jaar",
        "5": "4 \u2013 5 jaar",
        "6": "4 \u2013 5 jaar",
        "7": "6 \u2013 12 jaar",
        "8": "6 \u2013 12 jaar",
        "9": "4 \u2013 5 jaar"
    },
    "Q62": {
        "0": "Schoolgaand \/ scholier",
        "1": "Schoolgaand \/ scholier",
        "2": "Schoolgaand \/ scholier",
        "3": "Schoolgaand \/ scholier",
        "4": "Schoolgaand \/ scholier",
        "5": "Schoolgaand \/ scholier",
        "6": "Schoolgaand \/ scholier",
        "7": "Schoolgaand \/ scholier",
        "8": "Schoolgaand \/ scholier",
        "9": "Schoolgaand \/ scholier"
    },
    "Q63": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "Q63A": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "Q64": {
        "0": "Lagere school\/basisschool",
        "1": "Lagere school\/basisschool",
        "2": "Lagere school\/basisschool",
        "3": "Lagere school\/basisschool",
        "4": "Lagere school\/basisschool",
        "5": "Lagere school\/basisschool",
        "6": "Lagere school\/basisschool",
        "7": "Lagere school\/basisschool",
        "8": "Lagere school\/basisschool",
        "9": "Lagere school\/basisschool"
    },
    "Q65": {
        "0": " ",
        "1": " ",
        "2": " ",
        "3": " ",
        "4": " ",
        "5": " ",
        "6": " ",
        "7": " ",
        "8": " ",
        "9": " "
    },
    "Q66_cijfers": {
        "0": "Wil niet zeggen",
        "1": "Wil niet zeggen",
        "2": 2612,
        "3": "Wil niet zeggen",
        "4": "Wil niet zeggen",
        "5": "Wil niet zeggen",
        "6": "Wil niet zeggen",
        "7": "Wil niet zeggen",
        "8": "Wil niet zeggen",
        "9": "Wil niet zeggen"
    },
    "provinc": {
        "0": "Onbekend",
        "1": "Onbekend",
        "2": "Zuid-Holland",
        "3": "Onbekend",
        "4": "Onbekend",
        "5": "Onbekend",
        "6": "Onbekend",
        "7": "Onbekend",
        "8": "Onbekend",
        "9": "Onbekend"
    },
    "nielsen": {
        "0": "onbekend",
        "1": "onbekend",
        "2": "West",
        "3": "onbekend",
        "4": "onbekend",
        "5": "onbekend",
        "6": "onbekend",
        "7": "onbekend",
        "8": "onbekend",
        "9": "onbekend"
    },
    "stedpc": {
        "0": "onbekend",
        "1": "onbekend",
        "2": "zeer sterk stedelijk (>=2500\/km2)",
        "3": "onbekend",
        "4": "onbekend",
        "5": "onbekend",
        "6": "onbekend",
        "7": "onbekend",
        "8": "onbekend",
        "9": "onbekend"
    },
    "weging22jun": {
        "0": 2057.684148,
        "1": 2378.906525,
        "2": 1198.684473,
        "3": 3470.463172,
        "4": 16.83671586,
        "5": 1026.437101,
        "6": 1240.299225,
        "7": 5785.620027,
        "8": 2522.865898,
        "9": 451.2156403
    },
    "VolgNr": {
        "0": 1,
        "1": 2,
        "2": 3,
        "3": 4,
        "4": 5,
        "5": 6,
        "6": 7,
        "7": 8,
        "8": 9,
        "9": 10
    },
    "Weekdag": {
        "0": "Zaterdag",
        "1": "Woensdag",
        "2": "Zaterdag",
        "3": "Zondag",
        "4": "Dinsdag",
        "5": "Zondag",
        "6": "Donderdag",
        "7": "Dinsdag",
        "8": "Zaterdag",
        "9": "Woensdag"
    },
    "Dagdeel": {
        "0": "Weekend",
        "1": "Onbekend",
        "2": "Weekend",
        "3": "Weekend",
        "4": "Onbekend",
        "5": "Weekend",
        "6": "Onbekend",
        "7": "Onbekend",
        "8": "Weekend",
        "9": "Onbekend"
    },
    "filter_$": {
        "0": "Not Selected",
        "1": "Not Selected",
        "2": "Not Selected",
        "3": "Not Selected",
        "4": "Not Selected",
        "5": "Not Selected",
        "6": "Not Selected",
        "7": "Not Selected",
        "8": "Not Selected",
        "9": "Not Selected"
    },
    "LeeftCat": {
        "0": "4 t\/m 11 jaar",
        "1": "4 t\/m 11 jaar",
        "2": "4 t\/m 11 jaar",
        "3": "4 t\/m 11 jaar",
        "4": "4 t\/m 11 jaar",
        "5": "4 t\/m 11 jaar",
        "6": "4 t\/m 11 jaar",
        "7": "4 t\/m 11 jaar",
        "8": "4 t\/m 11 jaar",
        "9": "4 t\/m 11 jaar"
    }
}
'''