/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package locker.room.kotlin

import kotlin.test.*
import org.assertj.core.api.Assertions.*

class LockerTest {
    @Test
    fun anInitialLockerIsUnlocked() {
      assertThat(true).isEqualTo(false)
    }
  
  }