/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package locker.room.kotlin

import kotlin.test.Test
import kotlin.test.assertTrue

class LockerTest {
    @Test
    fun anInitialLockerIsUnlocked() {
      assertTrue(false)
    }
  
  }