[tool.poetry]
name = "DataProcessor"
version = "0.1.0"
description = "This kata practices TDD"
authors = ["Your name  <your@email.com>"]
package-mode = false

[tool.poetry.dependencies]
python = ">=3.10.0,<3.13"

pyhamcrest = "^2.1.0"
pytest-watch = "^4.2.0"
streamlit = "^1.38.0"
pandas = "^2.2.2"
openpyxl = "^3.1.5"
plotly-express = "^0.4.1"




[tool.group.poetry.dev.dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
