[tool.poetry]
name = "Train reservation kata"
version = "0.1.0"
description = "Booking reference service"
authors = ["Zeger Hendrikse <zegerh@yahoo.co.uk>"]
package-mode = false

[tool.poetry.dependencies]
python = ">=3.10.0,<3.13"
pyhamcrest = "^2.1.0"
pytest-watch = "^4.2.0"
cherrypy = "^18.10.0"

[tool.poetry.group.dev.dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
